# .github/workflows/feature.yml
name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  sonar:
     uses: ./.github/workflows/sonar.yml
     needs: build
     secrets: inherit     

  test:
    uses: ./.github/workflows/test.yml
    needs: sonar
    secrets: inherit  

  imagepush:
    uses: ./.github/workflows/imagepush.yml
    needs: test
    secrets: inherit  
